author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /ethica-naturalis-seu-documenta-moralia
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    deep_zoom: true
    extra_js:
    - volume-page.js
    - hammer.min.js
    - deepzoom.js
    - openseadragon.min.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://readux.ecds.emory.edu/books/readux:sz4mm/pages/readux:sz4nr/single-page/
image_size:
  page:
    height: 1000
    width: 842
  small-thumbnail:
    height: 100
    width: 84
  thumbnail:
    height: 300
    width: 252
permalink: pretty
publication_info:
  author: Weigel, Johann Christoph, 1661-1726, author, publisher.; Luiken, Jan, 1649-1712,
    illustrator.; Luiken, Caspar, 1672-1708, illustrator.
  date: '2018'
  editors:
  - Jesse Pearlman Karlsberg
  tei_xml: tei.xml
  title: Ethica naturalis, seu, Documenta moralia e variis rerum naturalium proprietatib[us],
    virtutum vitiorumq[ue] symbolicis imaginibus collecta // Ethica naturalis, an
    annotated digital edition
show_annotation_author: true
source_info:
  author: Weigel, Johann Christoph, 1661-1726, author, publisher.; Luiken, Jan, 1649-1712,
    illustrator.; Luiken, Caspar, 1672-1708, illustrator.
  date: '1700'
  pdf_url: https://readux.ecds.emory.edu/books/readux:sz4mm/pdf/
  title: Ethica naturalis, seu, Documenta moralia e variis rerum naturalium proprietatib[us],
    virtutum vitiorumq[ue] symbolicis imaginibus collecta // Ethica naturalis
  url: https://readux.ecds.emory.edu/books/readux:sz4mm/
  via_readux: true
tagline: ', an annotated digital edition'
title: Ethica naturalis, seu, Documenta moralia e variis rerum naturalium proprietatib[us],
  virtutum vitiorumq[ue] symbolicis imaginibus collecta // Ethica naturalis
url: https://jpkarlsberg.github.io
version: 0.7
